### PR TITLE
Line plot labels

### PR DESCRIPTION
**Pull request by skhilton**
This commit labels the x-axis of the context and focus plot by the `label_site` column but orders them by the `site` column. In this way, you can have a custom numbering like H3 numbering for HA or HxB2 numbering for HIV

### CODE REVIEW

**Review by huddlej — APPROVED** [review]
I can't believe how simple this PR is for something we agonized over for so long. So cool.

**Comment by huddlej** [comment]
It occurred to me that this code might break when we merge into the dropdown menu branch with its refactored plotting logic. Do you want to merge this here to master now or wait until we've merged the dropdown?

I'm slightly in favor of merging now to master...

**Comment by huddlej** [comment]
Also, I think this closes #11.

**Comment by skhilton** [comment]
I am in favor of merging now into master. I am going to pull everything from master into my `dropdown-menu` branch soon so I can rectify those conflicts sooner rather than later.

**Pull request merged**
